# -*- coding: utf-8 -*-
"""pythonDay_3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19qDfOhu176N6RW4tqQQBfupPyboLicBb
"""

import numpy as np
import pandas as pd

n1 = np.array([{1,2},{3,4}])

df = pd.DataFrame(n1, columns=['First Column','Second Column'])

# Syntax
# df = pd.read_csv(file)
# df = pd.read_excel(file,sheet_name='sheet_name')

#dataframe_nfhs = pd.read_csv('/content/Dist_Nfhs5_Sample.xlsx')
dataframe_nfhs = pd.read_excel('/content/Dist_Nfhs5_Sample.xlsx')

dataframe_nfhs.shape

# Shape of dataframe

# Syntax
# df.shape

print('Shape of dataframe is :',dataframe_nfhs.shape)
print('Number of rows :',dataframe_nfhs.shape[0])
print('Number of columns :',dataframe_nfhs.shape[1])

dataframe_nfhs.head()

dataframe_nfhs.tail()

print(dataframe_nfhs.info())

print(dataframe_nfhs.columns)

print(dataframe_nfhs.columns(3))

dataframe_nfhs.columns[1]

series_dis = dataframe_nfhs['District']

dataframe_nfhs.loc[:, ['District', 'Division', 'All women age 15-49 years who are anaemic']]

dataframe_nfhs.iloc[:,1]

dataframe_nfhs.iloc[:,3]

dataframe_nfhs.iloc[6,7:19]

dataframe_nfhs.loc[(0,3), ('District', 'All women age 15-49 years who are anaemic')]

dist_unique = dataframe_nfhs['District'].unique()
print(dist_unique)

df_div = dataframe_nfhs[dataframe_nfhs['Division'] == 'Bangalore']
df_div.head()

df_div = dataframe_nfhs[(dataframe_nfhs['Division'] == 'Bangalore') &
          (dataframe_nfhs['All women age 15-49 years who are anaemic']> 39)]
df_div.head(1)

print('Minimum is:',
      dataframe_nfhs['All women age 15-49 years who are anaemic'].min())
print('Maximum is:',
      dataframe_nfhs['All women age 15-49 years who are anaemic'].max())
print('Mean is:',
      dataframe_nfhs['All women age 15-49 years who are anaemic'].mean())
print('Standard Deviation is:',
      dataframe_nfhs['All women age 15-49 years who are anaemic'].std())
print('Median is:',
      dataframe_nfhs['All women age 15-49 years who are anaemic'].median())

dictagg = {'All women age 15-49 years who are anaemic': 'min',
           'Women who are overweight or obese (BMI ≥25.0 kg/m2)': 'count'}
df_div_agg = dataframe_nfhs.groupby(by=['Division']).agg(dictagg)
df_div_agg.head(4)

dataframe_nfhs_edit = dataframe_nfhs[['District',
                                      'All women age 15-49 years who are anaemic',
                                      'Children age 6-59 months who are anaemic (<11.0 g/dl)']]

df_pop = pd.read_excel('/content/Dist_Nfhs5_Sample.xlsx',
                                                             sheet_name='Population')

df_merge = pd.merge(left = dataframe_nfhs_edit,
                                                          right = df_pop,
                                                          left_on = 'District',
                                                          right_on = 'District',
                                                          how = 'left')
print(df_merge.head())