# -*- coding: utf-8 -*-
"""time_series_graph.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BgC9LBwAd6QIhvSR9EhzwP96xWk83KuR
"""

import pandas as pd

import numpy as np

import matplotlib.pyplot as plt

import seaborn as sns

df=pd.read_csv('/content/Hospital_Finance.csv')

!pip install fbprophet

from prophet import Prophet

df.tail(150)

df['Date']=pd.to_datetime(df['Date'],format='%d-%m-%Y')

df.head()

ts_data_edit = df[['Date','Revenue']]
ts_data_edit.rename(columns={'Date':'ds','Revenue':'y'},inplace=True)
model=Prophet()
model.fit(ts_data_edit)

#make future prediction
future=model.make_future_dataframe(periods=30)
forecast = model.predict(future)

#visualize the forecast
from prophet.plot import add_changepoints_to_plot
import matplotlib.pyplot as plt
fig = model.plot(forecast)

cols = ["Expenses","Revenue"]
listResult = []
for i in cols:
  ts_data_edit = df[['Date',i]]
  ts_data_edit.rename(columns={'Date':'ds',i:'y'},inplace=True)
  model=Prophet()
  model.fit(ts_data_edit)

  #make future prediction
  future=model.make_future_dataframe(periods=30)
  forecast = model.predict(future)
  forecast_filter = forecast[['ds','yhat', 'yhat_lower', 'yhat_upper']].tail(30)
  forecast_filter["Variable"] = i
  listResult.append(forecast_filter)
  #visualize the forecast
  from prophet.plot import add_changepoints_to_plot
  import matplotlib.pyplot as plt
  fig = model.plot(forecast)

forecast.columns

pd.concat(listResult).to_csv("forecast.csv")

