# -*- coding: utf-8 -*-
"""Untitled13.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19B4g-GnBetFttsqlH0ERMb6BvvwOank1
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from prophet import Prophet
import seaborn as sns

df = pd.read_csv('/content/SalesDaily (1).csv')

!pip install fbprophet

from prophet import Prophet

df['Date']=pd.to_datetime(df['Date'],format='%d-%m-%Y')

#creat and fit prophet model
ts_data_edit = df[['Date','M01AE']]
ts_data_edit.rename(columns={'Date':'ds','M01AE':'y'},inplace=True)
model=Prophet()
model.fit(ts_data_edit)

#make future prediction
future=model.make_future_dataframe(periods=30)
forecast = model.predict(future)

#visualize the forecast
from prophet.plot import add_changepoints_to_plot
import matplotlib.pyplot as plt
fig = model.plot(forecast)

